server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML #LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: # 如果没有密码，可以留空
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    gateway:
      routes:
        - id: captcha-service
          uri: http://localhost:8081
          predicates:
            - Path=/gen/**, /check/**, /login/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
captcha:
  expire:
    default: 10000
    # 文字点选验证码 过期时间设置大一点
    WORD_IMAGE_CLICK: 60000
  secondary:
    enabled: false
  # 初始化默认模板文件
  init-default-resource: true
  local-cache-enabled: true
  local-cache-size: 20

cors:
  controlAllowHeaders: "*"
  controlAllowMethods: "*"
  controlAllowOrigin: "*"

jwt:
  secret: A2D5F8G1J3K6M9P2R5T8W0Y3C5F8H2J6
